package com.olegsh.crudauto.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.olegsh.crudauto.model.Driver;
import com.olegsh.crudauto.model.Vehicle;

import com.olegsh.crudauto.model.DriverDao;
import com.olegsh.crudauto.model.VehicleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig driverDaoConfig;
    private final DaoConfig vehicleDaoConfig;

    private final DriverDao driverDao;
    private final VehicleDao vehicleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        driverDaoConfig = daoConfigMap.get(DriverDao.class).clone();
        driverDaoConfig.initIdentityScope(type);

        vehicleDaoConfig = daoConfigMap.get(VehicleDao.class).clone();
        vehicleDaoConfig.initIdentityScope(type);

        driverDao = new DriverDao(driverDaoConfig, this);
        vehicleDao = new VehicleDao(vehicleDaoConfig, this);

        registerDao(Driver.class, driverDao);
        registerDao(Vehicle.class, vehicleDao);
    }
    
    public void clear() {
        driverDaoConfig.clearIdentityScope();
        vehicleDaoConfig.clearIdentityScope();
    }

    public DriverDao getDriverDao() {
        return driverDao;
    }

    public VehicleDao getVehicleDao() {
        return vehicleDao;
    }

}
